// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDRm59nE_z-Y_fSy__hH2o6qMoczioPnc',
    appId: '1:196382341550:web:307311556ca060b663703f',
    messagingSenderId: '196382341550',
    projectId: 'esnafpanel-mobile-6911c',
    authDomain: 'esnafpanel-mobile-6911c.firebaseapp.com',
    storageBucket: 'esnafpanel-mobile-6911c.firebasestorage.app',
    measurementId: 'G-FERCDDMH0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8P8y_g1F54Po4zydHkZ5AAEQH--kkdnI',
    appId: '1:196382341550:android:357081458bc77a8363703f',
    messagingSenderId: '196382341550',
    projectId: 'esnafpanel-mobile-6911c',
    storageBucket: 'esnafpanel-mobile-6911c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB7Ov2og8daPYbb9tuAdBa1kzDU8JvXL4',
    appId: '1:196382341550:ios:9fdcaf3aab22b65463703f',
    messagingSenderId: '196382341550',
    projectId: 'esnafpanel-mobile-6911c',
    storageBucket: 'esnafpanel-mobile-6911c.firebasestorage.app',
    iosBundleId: 'com.example.esnafpanelMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB7Ov2og8daPYbb9tuAdBa1kzDU8JvXL4',
    appId: '1:196382341550:ios:9fdcaf3aab22b65463703f',
    messagingSenderId: '196382341550',
    projectId: 'esnafpanel-mobile-6911c',
    storageBucket: 'esnafpanel-mobile-6911c.firebasestorage.app',
    iosBundleId: 'com.example.esnafpanelMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDRm59nE_z-Y_fSy__hH2o6qMoczioPnc',
    appId: '1:196382341550:web:d840a8f8d7d0ceb263703f',
    messagingSenderId: '196382341550',
    projectId: 'esnafpanel-mobile-6911c',
    authDomain: 'esnafpanel-mobile-6911c.firebaseapp.com',
    storageBucket: 'esnafpanel-mobile-6911c.firebasestorage.app',
    measurementId: 'G-KPTYJMSBHG',
  );
}