name: esnafpanel_mobile
description: Flutter projesi (Hasan için özel yapı)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  google_sign_in: ^6.2.1
  flutter_dotenv: ^5.1.0
  fl_chart: ^0.66.2
  in_app_purchase: ^3.1.7
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.7.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
